/* The following code was generated by JFlex 1.7.0 */

package scanner;

import java_cup.runtime.Symbol;
import parser.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>./scanner/scanner.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\22\1\24\1\1\1\23\22\0\1\5\1\0\1\20"+
    "\4\0\1\25\1\10\1\12\1\11\1\60\1\67\1\16\1\17\1\64"+
    "\1\13\11\2\1\56\1\4\1\62\1\57\1\61\2\0\1\26\1\46"+
    "\1\52\1\30\1\15\1\47\1\45\1\42\1\35\1\54\1\55\1\43"+
    "\1\37\1\27\1\31\1\44\1\3\1\32\1\41\1\33\1\51\1\36"+
    "\1\50\1\14\1\53\1\3\1\65\1\21\1\66\1\63\2\0\1\26"+
    "\1\46\1\52\1\30\1\15\1\47\1\45\1\42\1\35\1\54\1\55"+
    "\1\43\1\37\1\27\1\31\1\44\1\3\1\32\1\41\1\33\1\51"+
    "\1\36\1\50\1\14\1\53\1\3\1\6\1\0\1\7\7\0\1\24"+
    "\252\0\2\34\115\0\1\40\u1ea8\0\1\24\1\24\u0100\0\1\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\3\1\4\1\11\1\12\2\1\6\4"+
    "\1\1\3\4\1\1\11\4\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\3\0\2\25"+
    "\1\26\1\27\1\0\1\2\1\0\1\30\1\31\1\25"+
    "\3\4\1\32\1\33\1\0\1\34\1\0\1\35\3\0"+
    "\1\36\1\0\7\4\1\37\1\4\1\40\1\4\1\41"+
    "\1\4\1\42\2\4\1\43\1\44\1\43\1\44\2\4"+
    "\3\0\20\4\1\27\4\4\1\45\1\46\1\47\1\50"+
    "\1\51\1\0\1\52\1\0\1\52\2\0\1\53\1\4"+
    "\1\54\1\4\7\0\1\55\1\0\1\56\2\4\1\57"+
    "\2\4\1\60\7\4\1\61\1\0\1\61\1\4\1\62"+
    "\1\63\1\41\1\0\1\43\1\4\1\43\7\4\1\64"+
    "\5\4\1\27\3\4\1\26\2\0\1\4\1\65\1\33"+
    "\1\0\4\4\1\66\1\67\3\4\1\70\2\0\2\4"+
    "\1\0\15\4\1\71\1\2\5\4\2\0\1\4\1\0"+
    "\5\4\1\27\1\4\1\72\1\4\1\73\1\74\1\41"+
    "\2\4\1\75\1\0\1\4\2\76\3\4\1\0\3\4"+
    "\1\0\1\4\1\77\1\4\1\0\3\4\1\0\1\100"+
    "\1\4\1\101";

  private static int [] zzUnpackAction() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\340\0\u01c0\0\u01f8\0\u0230\0\340\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658"+
    "\0\u0690\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818"+
    "\0\340\0\u0850\0\u0888\0\u08c0\0\340\0\340\0\340\0\340"+
    "\0\340\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u01c0\0\340\0\u0a80\0\340\0\u0ab8\0\u0af0\0\u0b28\0\u0b60"+
    "\0\u0b98\0\340\0\u0bd0\0\u0348\0\340\0\u0c08\0\340\0\u0c40"+
    "\0\u0c78\0\u0cb0\0\340\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\u0dc8"+
    "\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0188\0\u0f18\0\u0188"+
    "\0\u0f50\0\u0188\0\u0f88\0\u0fc0\0\u0ff8\0\340\0\u1030\0\u0188"+
    "\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0"+
    "\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340\0\u1378\0\u13b0"+
    "\0\u13e8\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570"+
    "\0\u15a8\0\u15e0\0\340\0\340\0\340\0\340\0\340\0\340"+
    "\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u0af0\0\u1730\0\u0188"+
    "\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u18b8\0\u18f0"+
    "\0\340\0\u1928\0\u0188\0\u1960\0\u1998\0\u0188\0\u19d0\0\u1a08"+
    "\0\u0188\0\u1a40\0\u1a78\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58\0\u1b90"+
    "\0\u1bc8\0\u1c00\0\u1c38\0\u1c70\0\u0188\0\u0188\0\340\0\u1ca8"+
    "\0\340\0\u1ce0\0\u0188\0\u1d18\0\u1d50\0\u1d88\0\u1dc0\0\u1df8"+
    "\0\u1e30\0\u1e68\0\u1ea0\0\u1ed8\0\u1f10\0\u1f48\0\u1f80\0\u1fb8"+
    "\0\u1ff0\0\u2028\0\u2060\0\u2098\0\u20d0\0\u20d0\0\u2108\0\u2140"+
    "\0\u0188\0\u2178\0\u2178\0\u21b0\0\u21e8\0\u2220\0\u2258\0\u0188"+
    "\0\u0188\0\u2290\0\u22c8\0\u2300\0\u0188\0\u2338\0\u2370\0\u23a8"+
    "\0\u23e0\0\u2418\0\u2450\0\u2488\0\u24c0\0\u24f8\0\u2530\0\u2568"+
    "\0\u25a0\0\u25d8\0\u2610\0\u2648\0\u2680\0\u26b8\0\u26f0\0\u0188"+
    "\0\u0a80\0\u2728\0\u2760\0\u2798\0\u27d0\0\u2808\0\u2840\0\u2878"+
    "\0\u28b0\0\u28e8\0\u2920\0\u2958\0\u2990\0\u29c8\0\u2a00\0\u2a38"+
    "\0\u2a70\0\u0188\0\u2aa8\0\u0188\0\u0188\0\u2220\0\u2ae0\0\u2b18"+
    "\0\u0188\0\u2b50\0\u2b88\0\340\0\u0188\0\u2bc0\0\u2bf8\0\u2c30"+
    "\0\u2c68\0\u2ca0\0\u2cd8\0\u2d10\0\u2d48\0\u2d80\0\u0188\0\u2db8"+
    "\0\u2df0\0\u2e28\0\u2e60\0\u2e98\0\u2ed0\0\u0188\0\u2f08\0\u0188";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\6\1\12\1\5"+
    "\1\13\1\14\1\15\1\16\1\10\1\17\1\20\1\21"+
    "\1\22\1\5\2\6\1\0\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\10\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\3\10\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\20\0\1\62\71\0"+
    "\1\63\72\0\1\64\133\0\1\6\3\0\1\6\14\0"+
    "\2\6\46\0\1\7\1\65\7\0\1\7\1\65\1\66"+
    "\1\0\1\67\6\0\6\65\1\0\3\65\1\0\15\65"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\15\10\12\0"+
    "\7\71\1\72\60\71\11\0\1\73\67\0\1\74\60\0"+
    "\1\75\1\65\7\0\1\75\1\76\1\66\1\0\1\67"+
    "\6\0\6\65\1\0\3\65\1\0\15\65\12\0\2\70"+
    "\2\10\7\0\1\10\1\77\1\10\3\0\1\70\2\0"+
    "\1\70\1\0\1\10\1\100\4\10\1\70\3\10\1\70"+
    "\2\10\1\101\12\10\30\0\1\102\53\0\1\103\10\0"+
    "\1\103\54\0\20\104\1\105\1\106\1\107\1\110\44\104"+
    "\21\111\1\112\1\113\1\114\1\111\1\0\42\111\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\1\10\1\115\2\10\1\116\1\10\1\70\3\10\1\70"+
    "\1\117\4\10\1\120\7\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\3\10\1\121"+
    "\2\10\1\70\1\122\2\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\2\10\1\123\3\0\1\70\2\0\1\70"+
    "\1\0\3\10\1\124\2\10\1\70\1\125\2\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\4\10\1\126\1\10\1\70\3\10"+
    "\1\70\5\10\1\127\1\130\6\10\12\0\2\70\2\10"+
    "\7\0\2\10\1\131\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\3\10"+
    "\1\132\2\10\1\70\3\10\1\70\1\10\1\133\10\10"+
    "\1\134\2\10\41\0\1\135\17\0\1\136\20\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\1\10\1\137\4\10\1\70\3\10\1\70\6\10\1\140"+
    "\6\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\1\141\5\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\3\10\1\142\2\10\1\70\3\10"+
    "\1\70\15\10\27\0\1\143\15\0\1\144\6\0\1\145"+
    "\25\0\2\70\2\10\7\0\2\10\1\146\3\0\1\70"+
    "\2\0\1\70\1\0\5\10\1\147\1\70\3\10\1\70"+
    "\1\10\1\150\13\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\1\151\5\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\1\152\3\10\1\153"+
    "\1\10\1\70\3\10\1\70\10\10\1\154\4\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\3\10\1\155\2\10\1\70\3\10\1\70\15\10"+
    "\12\0\2\70\2\10\7\0\2\10\1\156\3\0\1\70"+
    "\2\0\1\70\1\0\6\10\1\70\3\10\1\70\15\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\3\10\1\157\2\10\1\70\1\160\2\10"+
    "\1\70\10\10\1\161\4\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\4\10\1\162"+
    "\1\10\1\70\1\163\2\10\1\70\1\10\1\164\13\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\1\10\1\165\4\10\1\70\3\10\1\166"+
    "\1\167\14\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\1\170\2\10\1\171\2\10"+
    "\1\70\3\10\1\70\1\10\1\172\13\10\71\0\1\173"+
    "\70\0\1\174\66\0\1\175\67\0\1\176\1\0\1\177"+
    "\6\0\20\62\1\0\1\62\2\0\44\62\23\0\1\200"+
    "\44\0\22\64\2\0\1\64\1\0\42\64\2\0\2\65"+
    "\7\0\3\65\10\0\6\65\1\0\3\65\1\0\15\65"+
    "\14\0\1\201\1\65\7\0\1\201\2\65\1\202\7\0"+
    "\6\65\1\0\3\65\1\0\15\65\2\0\1\202\11\0"+
    "\1\203\10\0\1\203\1\0\1\204\54\0\2\70\7\0"+
    "\3\70\10\0\6\70\1\0\3\70\1\0\15\70\12\0"+
    "\11\73\1\205\56\73\2\0\1\75\1\65\7\0\1\75"+
    "\2\65\1\0\1\67\6\0\6\65\1\0\3\65\1\0"+
    "\15\65\14\0\2\206\7\0\3\206\10\0\6\206\1\0"+
    "\3\206\1\0\15\206\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\5\10\1\207\1\70"+
    "\1\146\2\10\1\70\15\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\2\10\1\210"+
    "\3\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\6\10"+
    "\1\70\3\10\1\70\1\211\14\10\14\0\1\103\10\0"+
    "\1\103\1\0\1\212\52\0\1\104\1\213\16\104\1\214"+
    "\1\104\1\107\1\215\1\213\43\104\20\214\1\105\1\216"+
    "\1\107\45\214\22\217\1\113\1\220\1\217\1\221\42\217"+
    "\1\111\1\217\20\111\1\113\1\220\1\217\1\222\42\111"+
    "\22\0\1\113\2\0\1\221\42\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\2\10\1\223"+
    "\3\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\4\10"+
    "\1\224\1\10\1\70\3\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\2\10\1\130\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\3\10\1\70\1\225\14\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\5\10\1\226\1\70\3\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\3\10\1\70\2\10\1\130\12\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\3\10\1\70\1\227\14\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\3\10\1\70\7\10\1\230\5\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\1\10\1\231\1\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\6\10\1\70\3\10\1\70\13\10"+
    "\1\232\1\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\1\233\4\10\1\234\1\70"+
    "\3\10\1\70\3\10\1\235\5\10\1\236\3\10\12\0"+
    "\2\70\2\10\7\0\2\10\1\237\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\3\10\1\70\3\10\1\240\11\10"+
    "\45\0\1\241\7\0\1\242\24\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\5\10\1\243"+
    "\1\70\3\10\1\70\2\10\1\244\12\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\4\10\1\245\1\10\1\70\3\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\2\10\1\246\3\10\1\70\3\10\1\70\15\10"+
    "\45\0\1\247\66\0\1\250\67\0\1\251\10\0\1\251"+
    "\24\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\5\10\1\130\1\70\3\10\1\70\15\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\4\10\1\252\1\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\4\10\1\253\1\10\1\70\3\10"+
    "\1\70\2\10\1\253\12\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\5\10\1\254\7\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\6\10"+
    "\1\70\3\10\1\70\11\10\1\255\3\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\3\10\1\256\2\10\1\70\1\257\2\10\1\70\15\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\5\10\1\260"+
    "\7\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\5\10\1\261\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\6\10\1\70\3\10\1\70\4\10"+
    "\1\262\10\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\4\10\1\263\1\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\6\10\1\70\3\10"+
    "\1\70\2\10\1\240\12\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\1\10\1\264"+
    "\4\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\6\10"+
    "\1\70\1\265\2\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\5\10"+
    "\1\266\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\6\10"+
    "\1\70\1\267\2\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\5\10"+
    "\1\270\1\70\1\146\2\10\1\70\15\10\14\0\2\70"+
    "\7\0\2\70\1\271\10\0\6\70\1\0\3\70\1\0"+
    "\15\70\12\0\2\70\2\10\7\0\2\10\1\272\3\0"+
    "\1\70\2\0\1\70\1\0\6\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\6\10\1\70\3\10\1\70\1\240"+
    "\14\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\1\10\1\273\4\10\1\70\3\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\1\274\5\10\1\70\3\10"+
    "\1\70\15\10\14\0\1\201\1\65\7\0\1\201\2\65"+
    "\10\0\6\65\1\0\3\65\1\0\15\65\14\0\1\201"+
    "\10\0\1\201\56\0\1\203\1\65\7\0\1\203\1\65"+
    "\1\66\10\0\6\65\1\0\3\65\1\0\15\65\14\0"+
    "\1\275\10\0\1\275\2\0\1\276\41\0\1\276\7\0"+
    "\11\73\1\277\1\72\55\73\2\70\2\10\7\0\2\10"+
    "\1\300\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\2\10"+
    "\1\301\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\15\10\14\0\1\302\10\0\1\302\2\0"+
    "\1\303\41\0\1\303\7\0\20\213\1\0\1\213\1\107"+
    "\1\215\44\213\20\214\1\105\1\216\1\0\45\214\22\0"+
    "\1\107\45\0\1\214\1\0\20\214\3\0\43\214\22\217"+
    "\1\113\1\220\1\217\1\0\42\217\22\0\1\113\72\0"+
    "\1\221\42\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\1\304\5\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\3\10\1\305\2\10\1\70\3\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\5\10\1\306\1\70\3\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\1\10\1\155\4\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\2\10"+
    "\1\307\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\2\10\1\310\3\10"+
    "\1\70\3\10\1\70\2\10\1\311\12\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\3\10\1\70\10\10\1\312\4\10\12\0"+
    "\2\70\2\10\7\0\2\10\1\313\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\3\10\1\314\2\10\1\70\3\10\1\70\15\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\1\10\1\315\4\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\2\10\1\130\3\0"+
    "\1\70\2\0\1\70\1\0\6\10\1\70\3\10\1\70"+
    "\15\10\27\0\1\316\106\0\2\317\32\0\2\70\2\10"+
    "\7\0\2\10\1\320\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\6\10"+
    "\1\70\1\321\2\10\1\70\15\10\46\0\2\322\32\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\1\323\2\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\2\10\1\122\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\3\10\1\70\14\10\1\324\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\5\10\1\325\1\70\3\10\1\70\4\10\1\326"+
    "\4\10\1\327\3\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\6\10\1\70\1\10"+
    "\1\330\1\10\1\70\15\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\2\10\1\331\12\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\3\10"+
    "\1\130\2\10\1\70\3\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\1\332\2\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\3\10\1\70\7\10\1\333\5\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\3\10\1\70\11\10\1\334\3\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\5\10\1\335\1\70\3\10\1\70\15\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\1\10\1\130"+
    "\13\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\6\10\1\70\3\10\1\70\2\10"+
    "\1\336\12\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\6\10\1\70\1\122\2\10"+
    "\1\70\15\10\14\0\2\70\7\0\3\70\10\0\6\70"+
    "\1\0\3\70\1\247\15\70\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\1\130\14\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\1\337\14\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\4\10\1\340"+
    "\1\10\1\70\3\10\1\70\15\10\14\0\1\275\10\0"+
    "\1\275\54\0\11\73\1\277\1\341\55\73\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\4\10"+
    "\1\342\1\10\1\70\3\10\1\70\15\10\14\0\1\302"+
    "\10\0\1\302\54\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\6\10\1\70\3\10\1\70"+
    "\12\10\1\130\2\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\6\10\1\70\3\10"+
    "\1\70\2\10\1\343\12\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\4\10\1\344"+
    "\1\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\6\10"+
    "\1\70\3\10\1\70\11\10\1\146\3\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\4\10\1\345\1\10\1\70\3\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\1\146\5\10\1\70\3\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\4\10\1\346\1\10\1\70\3\10\1\70\15\10"+
    "\44\0\1\347\64\0\1\350\40\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\4\10\1\351"+
    "\1\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\1\10"+
    "\1\240\4\10\1\70\3\10\1\70\15\10\41\0\1\352"+
    "\40\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\1\10\1\353\4\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\2\10\1\346\3\0"+
    "\1\70\2\0\1\70\1\0\6\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\2\10\1\354\3\0"+
    "\1\70\2\0\1\70\1\0\6\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\4\10\1\355\1\10\1\70\3\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\2\10\1\356"+
    "\3\0\1\70\2\0\1\70\1\0\6\10\1\70\3\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\1\357\5\10\1\70\3\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\6\10\1\360\1\361\2\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\1\10\1\362\4\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\1\314\5\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\5\10\1\363\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\2\10"+
    "\1\364\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\2\10"+
    "\1\365\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\5\10\1\366\1\70"+
    "\3\10\1\70\15\10\12\0\2\70\2\10\7\0\3\10"+
    "\3\0\1\70\2\0\1\70\1\0\1\10\1\367\4\10"+
    "\1\70\3\10\1\70\15\10\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\10\10\1\357\4\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\6\10"+
    "\1\70\3\10\1\70\10\10\1\370\4\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\1\10\1\371\4\10\1\70\3\10\1\70\15\10\12\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\2\10\1\130\3\10\1\70\3\10\1\70\15\10"+
    "\61\0\1\372\35\0\1\247\52\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\6\10\1\373\6\10\57\0\1\374\22\0"+
    "\2\70\2\10\7\0\3\10\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\3\10\1\70\4\10\1\375\10\10"+
    "\12\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\11\10\1\376"+
    "\3\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\1\377\5\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\2\10\1\u0100\3\10\1\70\3\10"+
    "\1\70\15\10\12\0\2\70\2\10\7\0\3\10\3\0"+
    "\1\70\2\0\1\70\1\0\5\10\1\240\1\70\3\10"+
    "\1\70\15\10\14\0\2\70\7\0\3\70\10\0\6\70"+
    "\1\0\3\70\1\u0101\15\70\12\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\1\u0102\10\10\1\130\3\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\1\u0103\2\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\1\122\5\10\1\70\3\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\6\10\1\70\3\10\1\70\11\10\1\u0104\3\10\40\0"+
    "\1\u0105\41\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\1\u0106\5\10\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\5\10\1\324\1\70\3\10\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\6\10\1\70\2\10\1\u0107\1\70"+
    "\15\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\6\10\1\70\3\10\1\70\10\10"+
    "\1\u0108\4\10\54\0\1\u0109\25\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\6\10\1\70"+
    "\3\10\1\70\1\10\1\324\13\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\3\10"+
    "\1\u010a\2\10\1\70\3\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\3\10\3\0\1\70\2\0\1\70\1\0"+
    "\5\10\1\u010b\1\70\3\10\1\70\15\10\64\0\1\350"+
    "\15\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\6\10\1\70\3\10\1\70\11\10\1\240"+
    "\3\10\12\0\2\70\2\10\7\0\3\10\3\0\1\70"+
    "\2\0\1\70\1\0\4\10\1\u010c\1\10\1\70\3\10"+
    "\1\70\15\10\27\0\1\u010d\52\0\2\70\2\10\7\0"+
    "\3\10\3\0\1\70\2\0\1\70\1\0\1\10\1\u010e"+
    "\4\10\1\70\3\10\1\70\15\10\12\0\2\70\2\10"+
    "\7\0\3\10\3\0\1\70\2\0\1\70\1\0\3\10"+
    "\1\u010f\2\10\1\70\3\10\1\70\15\10\12\0\2\70"+
    "\2\10\7\0\2\10\1\u0110\3\0\1\70\2\0\1\70"+
    "\1\0\6\10\1\70\3\10\1\70\15\10\42\0\1\247"+
    "\37\0\2\70\2\10\7\0\3\10\3\0\1\70\2\0"+
    "\1\70\1\0\4\10\1\130\1\10\1\70\3\10\1\70"+
    "\15\10\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12096];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\3\1\1\11\3\1\1\11\33\1\1\11"+
    "\3\1\5\11\7\1\1\0\1\11\1\0\1\11\5\1"+
    "\1\11\1\1\1\0\1\11\1\0\1\11\3\0\1\11"+
    "\1\0\21\1\1\11\4\1\3\0\25\1\6\11\1\1"+
    "\1\0\1\1\2\0\4\1\7\0\1\11\1\0\17\1"+
    "\1\0\4\1\1\11\1\0\1\11\24\1\2\0\3\1"+
    "\1\0\12\1\2\0\2\1\1\0\24\1\2\0\1\1"+
    "\1\0\17\1\1\0\1\1\1\11\4\1\1\0\3\1"+
    "\1\0\3\1\1\0\3\1\1\0\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** For the backwards DFA of general lookahead statements */
  private boolean [] zzFin = new boolean [ZZ_BUFFERSIZE+1];

  /* user code: */
  private Symbol sym(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }
  private Symbol sym(int type, Object val) {
    return new Symbol(type, yyline+1, yycolumn+1, val);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 232) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return sym(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { TokenCollector.addError("ERROR_LEXICO", yytext(), yyline+1);
            } 
            // fall through
          case 66: break;
          case 2: 
            { /* skip */
            } 
            // fall through
          case 67: break;
          case 3: 
            { TokenCollector.add("LITERAL_ENTERO", yytext(), yyline+1);
  return sym(sym.INT_LIT, yytext());
            } 
            // fall through
          case 68: break;
          case 4: 
            { String s = yytext();
  if (s.length() > 127) {
    TokenCollector.addError("ERROR_IDENTIFICADOR_LONGITUD", s, yyline+1);
    return sym(sym.IDENT, s);  // sigue el flujo
  } else {
    TokenCollector.add("IDENTIFICADOR", s, yyline+1);
    return sym(sym.IDENT, s);
  }
            } 
            // fall through
          case 69: break;
          case 5: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.SEMI);
            } 
            // fall through
          case 70: break;
          case 6: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.LPAREN);
            } 
            // fall through
          case 71: break;
          case 7: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.TIMES);
            } 
            // fall through
          case 72: break;
          case 8: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.RPAREN);
            } 
            // fall through
          case 73: break;
          case 9: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.MINUS);
            } 
            // fall through
          case 74: break;
          case 10: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.DOT);
            } 
            // fall through
          case 75: break;
          case 11: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.COLON);
            } 
            // fall through
          case 76: break;
          case 12: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.EQ);
            } 
            // fall through
          case 77: break;
          case 13: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.PLUS);
            } 
            // fall through
          case 78: break;
          case 14: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.GT);
            } 
            // fall through
          case 79: break;
          case 15: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.LT);
            } 
            // fall through
          case 80: break;
          case 16: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.CARET);
            } 
            // fall through
          case 81: break;
          case 17: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.DIVIDE);
            } 
            // fall through
          case 82: break;
          case 18: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.LBRACK);
            } 
            // fall through
          case 83: break;
          case 19: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.RBRACK);
            } 
            // fall through
          case 84: break;
          case 20: 
            { TokenCollector.add("SEPARADOR", yytext(), yyline+1); return sym(sym.COMMA);
            } 
            // fall through
          case 85: break;
          case 21: 
            { TokenCollector.addError("ERROR_NUMERO_SEGUIDO_DE_TEXTO", yytext(), yyline+1);
            } 
            // fall through
          case 86: break;
          case 22: 
            { TokenCollector.addError("ERROR_REAL_PUNTO_COLA",  yytext(), yyline+1);
            } 
            // fall through
          case 87: break;
          case 23: 
            { TokenCollector.addError("ERROR_IDENTIFICADOR_SIMBOLO_ILEGAL", yytext(), yyline+1);
            } 
            // fall through
          case 88: break;
          case 24: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.IDENT, yytext());
            } 
            // fall through
          case 89: break;
          case 25: 
            { String s = yytext();
  if (s.matches("0[0-7]+")) {
    TokenCollector.add("LITERAL_OCTAL", s, yyline+1);
    return sym(sym.INT_LIT, s);
  } else {
    TokenCollector.addError("ERROR_OCTAL_INVALIDO", s, yyline+1);
  }
            } 
            // fall through
          case 90: break;
          case 26: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.DECR);
            } 
            // fall through
          case 91: break;
          case 27: 
            { TokenCollector.addError("ERROR_REAL_PUNTO_LIDER", yytext(), yyline+1);
            } 
            // fall through
          case 92: break;
          case 28: 
            { TokenCollector.add("LITERAL_STRING", yytext(), yyline+1);
  return sym(sym.STRING_LIT, yytext());
            } 
            // fall through
          case 93: break;
          case 29: 
            // general lookahead, find correct zzMarkedPos
            { int zzFState = 1;
              int zzFPos = zzStartRead;
              if (zzFin.length <= zzBufferL.length) { zzFin = new boolean[zzBufferL.length+1]; }
              boolean zzFinL[] = zzFin;
              while (zzFState != -1 && zzFPos < zzMarkedPos) {
                zzFinL[zzFPos] = ((zzAttrL[zzFState] & 1) == 1);
                zzInput = Character.codePointAt(zzBufferL, zzFPos, zzMarkedPos);
                zzFPos += Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMapL[zzInput] ];
              }
              if (zzFState != -1) { zzFinL[zzFPos++] = ((zzAttrL[zzFState] & 1) == 1); } 
              while (zzFPos <= zzMarkedPos) {
                zzFinL[zzFPos++] = false;
              }

              zzFState = 2;
              zzFPos = zzMarkedPos;
              while (!zzFinL[zzFPos] || (zzAttrL[zzFState] & 1) != 1) {
                zzInput = Character.codePointBefore(zzBufferL, zzFPos, zzStartRead);
                zzFPos -= Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMapL[zzInput] ];
              };
              zzMarkedPos = zzFPos;
            }
            { TokenCollector.addError("ERROR_STRING_SIN_CIERRE", yytext(), yyline+1);
            } 
            // fall through
          case 94: break;
          case 30: 
            // general lookahead, find correct zzMarkedPos
            { int zzFState = 3;
              int zzFPos = zzStartRead;
              if (zzFin.length <= zzBufferL.length) { zzFin = new boolean[zzBufferL.length+1]; }
              boolean zzFinL[] = zzFin;
              while (zzFState != -1 && zzFPos < zzMarkedPos) {
                zzFinL[zzFPos] = ((zzAttrL[zzFState] & 1) == 1);
                zzInput = Character.codePointAt(zzBufferL, zzFPos, zzMarkedPos);
                zzFPos += Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMapL[zzInput] ];
              }
              if (zzFState != -1) { zzFinL[zzFPos++] = ((zzAttrL[zzFState] & 1) == 1); } 
              while (zzFPos <= zzMarkedPos) {
                zzFinL[zzFPos++] = false;
              }

              zzFState = 2;
              zzFPos = zzMarkedPos;
              while (!zzFinL[zzFPos] || (zzAttrL[zzFState] & 1) != 1) {
                zzInput = Character.codePointBefore(zzBufferL, zzFPos, zzStartRead);
                zzFPos -= Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMapL[zzInput] ];
              };
              zzMarkedPos = zzFPos;
            }
            { TokenCollector.addError("ERROR_CHAR_SIN_CIERRE",   yytext(), yyline+1);
            } 
            // fall through
          case 95: break;
          case 31: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.DO);
            } 
            // fall through
          case 96: break;
          case 32: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.OR);
            } 
            // fall through
          case 97: break;
          case 33: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1);
  return sym(sym.IDENT, yytext());
            } 
            // fall through
          case 98: break;
          case 34: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.TO);
            } 
            // fall through
          case 99: break;
          case 35: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1);
  return sym(sym.IDENT, yytext());
            } 
            // fall through
          case 100: break;
          case 36: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.IF);
            } 
            // fall through
          case 101: break;
          case 37: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.ASSIGN);
            } 
            // fall through
          case 102: break;
          case 38: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.INCR);
            } 
            // fall through
          case 103: break;
          case 39: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.GE);
            } 
            // fall through
          case 104: break;
          case 40: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.LE);
            } 
            // fall through
          case 105: break;
          case 41: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.NE);
            } 
            // fall through
          case 106: break;
          case 42: 
            { TokenCollector.add("LITERAL_REAL", yytext(), yyline+1);
  return sym(sym.REAL_LIT, yytext());
            } 
            // fall through
          case 107: break;
          case 43: 
            { String s = yytext();
  if (s.matches("0[xX][0-9A-Fa-f]+")) {
    TokenCollector.add("LITERAL_HEX", s, yyline+1);
    return sym(sym.INT_LIT, s);
  } else {
    TokenCollector.addError("ERROR_HEX_INVALIDO", s, yyline+1);
  }
            } 
            // fall through
          case 108: break;
          case 44: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.END);
            } 
            // fall through
          case 109: break;
          case 45: 
            { TokenCollector.add("LITERAL_CHAR", yytext(), yyline+1);
  return sym(sym.CHAR_LIT, yytext());
            } 
            // fall through
          case 110: break;
          case 46: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.AND);
            } 
            // fall through
          case 111: break;
          case 47: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.NOT);
            } 
            // fall through
          case 112: break;
          case 48: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.DIV_KW);
            } 
            // fall through
          case 113: break;
          case 49: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.INT);
            } 
            // fall through
          case 114: break;
          case 50: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.VAR);
            } 
            // fall through
          case 115: break;
          case 51: 
            { TokenCollector.add("OPERADOR", yytext(), yyline+1); return sym(sym.MOD_KW);
            } 
            // fall through
          case 116: break;
          case 52: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.FOR);
            } 
            // fall through
          case 117: break;
          case 53: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.ELSE);
            } 
            // fall through
          case 118: break;
          case 54: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.READ);
            } 
            // fall through
          case 119: break;
          case 55: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.REAL);
            } 
            // fall through
          case 120: break;
          case 56: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.THEN);
            } 
            // fall through
          case 121: break;
          case 57: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.CHAR);
            } 
            // fall through
          case 122: break;
          case 58: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.BEGIN);
            } 
            // fall through
          case 123: break;
          case 59: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.WRITE);
            } 
            // fall through
          case 124: break;
          case 60: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.WHILE);
            } 
            // fall through
          case 125: break;
          case 61: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.RETURN);
            } 
            // fall through
          case 126: break;
          case 62: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.STRING);
            } 
            // fall through
          case 127: break;
          case 63: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.PROGRAM);
            } 
            // fall through
          case 128: break;
          case 64: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.FUNCTION);
            } 
            // fall through
          case 129: break;
          case 65: 
            { TokenCollector.add("PALABRA_RESERVADA", yytext(), yyline+1); return sym(sym.PROCEDURE);
            } 
            // fall through
          case 130: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
