
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIV_KW = 24;
  public static final int CHAR_LIT = 52;
  public static final int DIVIDE = 22;
  public static final int FUNCTION = 4;
  public static final int CHAR = 35;
  public static final int GE = 31;
  public static final int SEMI = 42;
  public static final int LPAREN = 37;
  public static final int DECR = 46;
  public static final int INCR = 45;
  public static final int INT = 33;
  public static final int FOR = 14;
  public static final int MINUS = 20;
  public static final int WRITE = 48;
  public static final int RPAREN = 38;
  public static final int NOT = 16;
  public static final int AND = 17;
  public static final int LT = 28;
  public static final int OR = 18;
  public static final int COMMA = 41;
  public static final int BEGIN = 6;
  public static final int PLUS = 19;
  public static final int ASSIGN = 32;
  public static final int IF = 9;
  public static final int CARET = 25;
  public static final int DOT = 44;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int IDENT = 49;
  public static final int EQ = 26;
  public static final int LBRACK = 39;
  public static final int MOD_KW = 23;
  public static final int REAL = 34;
  public static final int TIMES = 21;
  public static final int COLON = 43;
  public static final int ELSE = 11;
  public static final int READ = 47;
  public static final int RBRACK = 40;
  public static final int TO = 15;
  public static final int WHILE = 12;
  public static final int REAL_LIT = 51;
  public static final int THEN = 10;
  public static final int NE = 27;
  public static final int END = 7;
  public static final int STRING = 36;
  public static final int STRING_LIT = 53;
  public static final int INT_LIT = 50;
  public static final int GT = 29;
  public static final int VAR = 3;
  public static final int PROCEDURE = 5;
  public static final int DO = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "VAR",
  "FUNCTION",
  "PROCEDURE",
  "BEGIN",
  "END",
  "RETURN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "TO",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD_KW",
  "DIV_KW",
  "CARET",
  "EQ",
  "NE",
  "LT",
  "GT",
  "LE",
  "GE",
  "ASSIGN",
  "INT",
  "REAL",
  "CHAR",
  "STRING",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "SEMI",
  "COLON",
  "DOT",
  "INCR",
  "DECR",
  "READ",
  "WRITE",
  "IDENT",
  "INT_LIT",
  "REAL_LIT",
  "CHAR_LIT",
  "STRING_LIT"
  };
}

